spring.profiles.active=default
spring.application.name=sysfoo
app.version=1.0.0

# Estas tres deben tener la sintaxis ${...} para leer desde Docker
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

jakarta.persistence.sharedCache.mode=ENABLE_SELECTIVE